#!/usr/bin/env python
import torch
import torch.nn.functional as F
class model(torch.nn.Module):
    def __init__(self):
        super(model, self).__init__()
        self.Dense0 = torch.nn.Linear(2, 10)
        self.Dense1 = torch.nn.Linear(10, 10)
        self.Dense2 = torch.nn.Linear(10, 10)
        self.Dense3 = torch.nn.Linear(10, 10)
        self.Dense4 = torch.nn.Linear(10, 10)
        self.Dense5 = torch.nn.Linear(10, 10)
        self.Dense6 = torch.nn.Linear(10, 10)
        self.Dense7 = torch.nn.Linear(10, 10)
        self.Dense8 = torch.nn.Linear(10, 10)
        self.Dense9 = torch.nn.Linear(10, 10)
        self.Dense10 = torch.nn.Linear(10, 10)
        self.Dense11 = torch.nn.Linear(10, 10)
        self.Dense12 = torch.nn.Linear(10, 10)
        self.Dense13 = torch.nn.Linear(10, 10)
        self.Dense14 = torch.nn.Linear(10, 10)
        self.Dense15 = torch.nn.Linear(10, 10)
        self.Dense16 = torch.nn.Linear(10, 10)
        self.Dense17 = torch.nn.Linear(10, 10)
        self.Dense18 = torch.nn.Linear(10, 10)
        self.Dense19 = torch.nn.Linear(10, 10)
        self.Dense20 = torch.nn.Linear(10, 10)
        self.Dense21 = torch.nn.Linear(10, 10)
        self.Dense22 = torch.nn.Linear(10, 10)
        self.Dense23 = torch.nn.Linear(10, 10)
        self.Dense24 = torch.nn.Linear(10, 10)
        self.Dense25 = torch.nn.Linear(10, 10)
        self.Dense26 = torch.nn.Linear(10, 10)
        self.Dense27 = torch.nn.Linear(10, 10)
        self.Dense28 = torch.nn.Linear(10, 10)
        self.Dense29 = torch.nn.Linear(10, 10)
        self.Dense30 = torch.nn.Linear(10, 10)
        self.Dense31 = torch.nn.Linear(10, 1)
    def forward(self, x):
        x=self.Dense0(x)
        x=F.relu(self.Dense1(x))
        x=F.relu(self.Dense2(x))
        x=F.relu(self.Dense3(x))
        x=F.relu(self.Dense4(x))
        x=F.relu(self.Dense5(x))
        x=F.relu(self.Dense6(x))
        x=F.relu(self.Dense7(x))
        x=F.relu(self.Dense8(x))
        x=F.relu(self.Dense9(x))
        x=F.relu(self.Dense10(x))
        x=F.relu(self.Dense11(x))
        x=F.relu(self.Dense12(x))
        x=F.relu(self.Dense13(x))
        x=F.relu(self.Dense14(x))
        x=F.relu(self.Dense15(x))
        x=F.relu(self.Dense16(x))
        x=F.relu(self.Dense17(x))
        x=F.relu(self.Dense18(x))
        x=F.relu(self.Dense19(x))
        x=F.relu(self.Dense20(x))
        x=F.relu(self.Dense21(x))
        x=F.relu(self.Dense22(x))
        x=F.relu(self.Dense23(x))
        x=F.relu(self.Dense24(x))
        x=F.relu(self.Dense25(x))
        x=F.relu(self.Dense26(x))
        x=F.relu(self.Dense27(x))
        x=F.relu(self.Dense28(x))
        x=F.relu(self.Dense29(x))
        x=F.relu(self.Dense30(x))
        x=F.relu(self.Dense31(x))
        return x